/*
serverstat is a package automatically generated by ´gobi´. Happy hacking!
*/
package serverstat

import (
	"errors"
)

// MyserverstatExample is a example type automatically generated by ´gobi´.
type MyserverstatExample struct {
	id 	 int
	name string
}

// New creates a new *MyserverstatExample object
func New(id int, name string) (*MyserverstatExample, error) {
	if name == "" {
		return nil, errors.New("Name is empty.")
	}

	return &MyserverstatExample{id, name}, nil
}

// Id of the MyserverstatExample
func (ex MyserverstatExample) Id() int {
	return ex.id
}

// Name of the MyserverstatExample
func (ex MyserverstatExample) Name() string {
	return ex.name
}

// SetId for the MyserverstatExample
func (ex *MyserverstatExample) SetId(id int) {
	ex.id = id
}

// SetName for the MyserverstatExample
func (ex *MyserverstatExample) SetName(name string) {
	ex.name = name
}




